import os
from openai import AsyncOpenAI

openai_client = AsyncOpenAI(api_key="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")